export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen">
      {children}
    </main>
  );
}
